// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0jQVcogKnlr23ruc8b4xtJfJ0XZUqJ6A',
    appId: '1:79497201315:web:61531fbabaadfabd696116',
    messagingSenderId: '79497201315',
    projectId: 'uptodo-7d4b6',
    authDomain: 'uptodo-7d4b6.firebaseapp.com',
    storageBucket: 'uptodo-7d4b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9OKaY-oLTOd2aVC7ItTFNIvJ1L1TpD1Q',
    appId: '1:79497201315:ios:40db7e330e5ea1d1696116',
    messagingSenderId: '79497201315',
    projectId: 'uptodo-7d4b6',
    storageBucket: 'uptodo-7d4b6.firebasestorage.app',
    iosBundleId: 'com.example.uptodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9OKaY-oLTOd2aVC7ItTFNIvJ1L1TpD1Q',
    appId: '1:79497201315:ios:40db7e330e5ea1d1696116',
    messagingSenderId: '79497201315',
    projectId: 'uptodo-7d4b6',
    storageBucket: 'uptodo-7d4b6.firebasestorage.app',
    iosBundleId: 'com.example.uptodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0jQVcogKnlr23ruc8b4xtJfJ0XZUqJ6A',
    appId: '1:79497201315:web:a7ac112a1cdfd99d696116',
    messagingSenderId: '79497201315',
    projectId: 'uptodo-7d4b6',
    authDomain: 'uptodo-7d4b6.firebaseapp.com',
    storageBucket: 'uptodo-7d4b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv-rUhgSaAd0F8QCBpPaJUZNhKNef8C58',
    appId: '1:79497201315:android:da86d36fd6f04710696116',
    messagingSenderId: '79497201315',
    projectId: 'uptodo-7d4b6',
    storageBucket: 'uptodo-7d4b6.firebasestorage.app',
  );

}